language: cpp

sudo: required
dist: xenial
 
compiler:  
    - gcc

before_script:
    - sudo apt-get install build-essential
    - sudo apt-get install cmake
    - sudo apt-get install libopencv-dev

script:
    - mkdir -p build
    - cd build
    - cmake ..
    - make

